baseURL = "https://example.com"
disablePathToLower = true
languageCode = "en-us"
title = "docter"
theme = "docter"

[params]
  name = "docter"
  author = "org name"
  author_url= "https://github.com/edavidaja"
  repo_host = "Gitlab"
  repo = "https://gitlab.com/edavidaja/docter"
  logourl= ""
  logoalt= ""
  hosted_on= "netlify"
  hosted_on_url= "https://www.netlify.com"
